### ISSUE TITLE
Unknown error type: [8] unserialize(): Error at offset 0 of 360 bytes

### ISSUE THREAD

**Issue by jespersgaard** [reborncms/reborn#8]
hi

i keep getting this error:

Unknown error type: [8] unserialize(): Error at offset 0 of 360 bytes
{{ CMS }} » heart\vendor\cartalyst\sentry\src\Cartalyst\Sentry\Cookies\NativeCookie.php
return unserialize($_COOKIE[$this->getKey()]);

**Comment by Mr-Zer0** [comment]
Thanks for your issue. We will fix it as soon as possible.

**Comment by Mr-Zer0** [comment]
When do you get this error?

**Comment by jespersgaard** [comment]
I just tried it again today, and now the error is gone?!
maybe it was my local server playing a prank on me.

please just close this one, thanks :-)
